apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.cadadvisor.name }}-service
    namespace: {{ .Values.global.monitoringNs }}
    labels:
        name: {{ .Values.cadadvisor.name }}
spec:
    clusterIP: None
    ports:
        - name: {{ .Values.cadadvisor.portName }}
          port: 8080
          targetPort: {{ .Values.cadadvisor.portName }}
    selector:
        name: {{ .Values.cadadvisor.name }}