
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.postgres.dbSecret }}
    namespace: {{ .Values.configMap.namespace }}
data:
    username: {{ .Values.postgres.dbOwner | b64enc }}
    password: {{ .Values.postgres.dbPassword | b64enc }}
type: kubernetes.io/basic-auth