
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.postgres.dbSecret }}
    namespace: {{ .Values.configMap.namespace }}
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "application-ns"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
data:
    username: {{ .Values.postgres.dbOwner | b64enc }}
    password: {{ .Values.postgres.dbPassword | b64enc }}
type: kubernetes.io/basic-auth