apiVersion: v2
name: backend-chart
description: common chart for installation of backend infrastructure
version: 1.0.0
appVersion: 1.0.0
dependencies:
    - name: helm-keycloak
      version: 1.0.0
      repository: "file://./charts/helm-keycloak"
      condition: false
    - name: helm-cert-manager
      version: 1.0.0
      repository: "file://./charts/helm-cert-manager"
      condition: true
    - name: helm-users-db
      version: 1.0.0
      repository: "file://./charts/helm-users-db"
      condition: true
    -   name: helm-prometheus
        version: 0.79.2
        repository: "file://./charts/helm-prometheus"
        condition: true
    -   name: helm-prometheus-alertmanager
        version: 0.79.2
        repository: "file://./charts/helm-prometheus-alertmanager"
        condition: true
    -   name: helm-prometheus-crds
        version: 0.79.2
        repository: "file://./charts/helm-prometheus-crds"
        condition: true