{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.clusterRoleName }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - namespaces
      - events
      - pods
      - pods/log
      - persistentvolumeclaims
      - services
      - serviceaccounts/token
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - "monitoring.coreos.com"
      - "postgresql.cnpg.io"
    resources:
      - prometheusrules
      - servicemonitors
      - podmonitors
      - clusters
      - clusters/status
      - backups
      - backups/status
      - kubernetesrolebindings
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
{{- end -}}