apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.postgres.dbSecret }}
    namespace: {{ .Values.global.keycloakNs }}
data:
    username: {{ .Values.postgres.keycloakDBOwner | b64enc }}
    password: {{ .Values.postgres.keycloakDBPassword | b64enc }}
type: kubernetes.io/basic-auth