apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.keycloak.secretName }}
    namespace: {{ .Values.global.keycloakNs }}
data:
    KEYCLOAK_ADMIN: {{ .Values.keycloak.keycloakAdmin | b64enc }}
    KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.keycloakAdminPassword | b64enc }}
type: Opaque