apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.global.keycloakNs }}
  labels:
    app: {{ .Values.keycloak.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: https
      targetPort: http
      protocol: TCP
  selector:
    app: {{ .Values.keycloak.name }}