apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.global.keycloakNs }}
  labels:
    app: {{ .Values.keycloak.name }}
    {{- if .Values.monitoring.enabled }}
    {{ .Values.monitoring.monitoringLabelName }}: {{ .Values.monitoring.monitoringLabelValue }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: https
      targetPort: http
      protocol: TCP
    - port: {{ .Values.keycloak.metricsPort }}
      name: {{ .Values.keycloak.metricsPortName }}
      targetPort: {{ .Values.keycloak.metricsPortName }}
      protocol: TCP
  selector:
    app: {{ .Values.keycloak.name }}