apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.alertmanager.name }}-service
    namespace: {{ .Values.alertmanager.namespace }}
spec:
    ports:
        - name: {{ .Values.alertmanager.portName }}
          port: 9093
          targetPort: {{ .Values.alertmanager.portName }}
    selector:
        app.kubernetes.io/instance: {{ .Values.alertmanager.name }}
        app.kubernetes.io/name: alertmanager