apiVersion: v1
data: {}
kind: Secret
metadata:
    name: {{ .Values.alertmanager.name }}-service
    namespace: {{ .Values.alertmanager.namespace }}
stringData:
    alertmanager.yaml: |-
        "global":
          "resolve_timeout": "5m"
        "receivers":
        - "name": "email-notification"
          "email_configs":
            -  "to": "{{ .Values.email.emailSendTo }}"
               "from": "{{ .Values.email.emailSendFrom }}"
               "smarthost": "{{ .Values.email.host }}:{{ .Values.email.port }}"
               "auth_username": "{{ .Values.email.username }}"
               "auth_password": "{{ .Values.email.password }}"
               "require_tls": true
               "text": "You received alert notification: {{ .Values.global.rule.ruleName }}"
               "send_resolved": true
        "route":
          "group_by":
            - "alertname"
          "group_interval": "10s"
          "group_wait": "30s"
          "repeat_interval": "1m"
          "receiver": "email-notification"
type: Opaque