apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.kubeMetrics.name }}
    namespace: {{ .Values.global.monitoringNs }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: {{ .Values.kubeMetrics.name }}
    template:
        metadata:
            labels:
                app.kubernetes.io/name: {{ .Values.kubeMetrics.name }}
        spec:
            automountServiceAccountToken: true
            containers:
                - image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.15.0
                  livenessProbe:
                      httpGet:
                          path: /healthz
                          port: 8080
                      initialDelaySeconds: 5
                      timeoutSeconds: 5
                  name: {{ .Values.kubeMetrics.name }}
                  resources:
                      requests:
                          cpu: 50m
                          memory: 128Mi
                      limits:
                          cpu: 200m
                          memory: 256Mi
                  ports:
                      - containerPort: 8080
                        name: {{ .Values.kubeMetrics.portName }}
                      - containerPort: 8081
                        name: telemetry
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 8081
                      initialDelaySeconds: 5
                      timeoutSeconds: 5
                  securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                          drop:
                              - ALL
                      readOnlyRootFilesystem: true
                      runAsUser: 65534
            nodeSelector:
                kubernetes.io/os: linux
            serviceAccountName: {{ .Values.kubeMetrics.saName }}