apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.kubeMetrics.name }}-service
    namespace: {{ .Values.global.monitoringNs }}
    labels:
        app.kubernetes.io/name: {{ .Values.kubeMetrics.name }}
spec:
    clusterIP: None
    ports:
        - name: {{ .Values.kubeMetrics.portName }}
          port: 8080
          targetPort: {{ .Values.kubeMetrics.portName }}
        - name: telemetry
          port: 8081
          targetPort: telemetry
    selector:
        app.kubernetes.io/name: {{ .Values.kubeMetrics.name }}