apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: prometheus-operator
        app.kubernetes.io/version: {{ .Values.prometheus.version }}
    name: prometheus-operator
    namespace: {{ .Values.prometheus.namespace }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/component: controller
            app.kubernetes.io/name: prometheus-operator
    template:
        metadata:
            annotations:
                kubectl.kubernetes.io/default-container: prometheus-operator
            labels:
                app.kubernetes.io/component: controller
                app.kubernetes.io/name: prometheus-operator
                app.kubernetes.io/version: {{ .Values.prometheus.version }}
        spec:
            automountServiceAccountToken: true
            containers:
                - args:
                      - --kubelet-service=kube-system/kubelet
                      - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v{{ .Values.prometheus.version }}
                      - --kubelet-endpoints=true
                      - --kubelet-endpointslice=false
                  env:
                      - name: GOGC
                        value: "30"
                  image: quay.io/prometheus-operator/prometheus-operator:v{{ .Values.prometheus.version }}
                  name: prometheus-operator
                  ports:
                      - containerPort: 8080
                        name: http
                  resources:
                      limits:
                          cpu: 200m
                          memory: 200Mi
                      requests:
                          cpu: 100m
                          memory: 100Mi
                  securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                          drop:
                              - ALL
                      readOnlyRootFilesystem: true
            securityContext:
                runAsNonRoot: true
                runAsUser: 65534
                seccompProfile:
                    type: RuntimeDefault
            serviceAccountName: {{ .Values.prometheus.prometheusOperatorRoleName }}