apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ .Values.prometheus.prometheusRoleName }}
    namespace: {{ .Values.prometheus.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: {{ .Values.prometheus.prometheusRoleName }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ .Values.prometheus.prometheusRoleName }}
subjects:
    - kind: ServiceAccount
      name: {{ .Values.prometheus.prometheusRoleName }}
      namespace: {{ .Values.prometheus.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{ .Values.prometheus.prometheusRoleName }}
rules:
    - apiGroups: [""]
      resources:
          - nodes
          - nodes/metrics
          - services
          - endpoints
          - pods
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources:
          - configmaps
      verbs: ["get"]
    - apiGroups:
          - discovery.k8s.io
      resources:
          - endpointslices
      verbs: ["get", "list", "watch"]
    - apiGroups:
          - networking.k8s.io
      resources:
          - ingresses
      verbs: ["get", "list", "watch"]
    - nonResourceURLs: ["/metrics"]
      verbs: ["get"]