---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
    name: {{ .Values.prometheus.name }}
    namespace: {{ .Values.prometheus.namespace }}
spec:
    serviceAccountName: {{ .Values.prometheus.prometheusRoleName }}
    serviceMonitorSelector:
        matchLabels:
            app-monitoring: {{ .Values.prometheus.serviceMonitorLabel }}
    serviceMonitorNamespaceSelector: {}
    resources:
        requests:
            cpu: 300m
            memory: 200Mi
        limits:
            cpu: 500m
            memory: 1Gi
    replicas: 2
    logLevel: info
    logFormat: logfmt
    retention: 2h
    scrapeInterval: 30s
    securityContext:
        fsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
    ruleSelector:
        matchLabels:
            alertmanager: {{ .Values.global.alertmanagerName }}
            monitoring: prometheus
    alerting:
        alertmanagers:
            -   namespace: {{ .Values.prometheus.namespace }}
                name: {{ .Values.global.alertmanagerName }}-service
                port: web
    storage:
        volumeClaimTemplate:
            spec:
                resources:
                    requests:
                        storage: 200Mi