{{- if .Values.global.migrationEnabled -}}
apiVersion: batch/v1
kind: Job
metadata:
    name: {{ .Values.ssl.jobName }}
    namespace: {{ .Values.kafka.namespace }}
spec:
{{/*    ttlSecondsAfterFinished: 120*/}}
    backoffLimit: 2
    template:
        spec:
            restartPolicy: Never
            containers:
                - name: {{ .Values.ssl.jobName }}
                  image: "{{ .Values.migration.imagePrefix }}/{{ .Values.migration.name}}:{{ .Values.migration.version}}"
                  envFrom:
                      - configMapRef:
                            name: {{ .Values.global.usersDbConfigMap }}
                  env:
                      - name: DB_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Values.global.usersDbSecret }}
                                key: username
                      - name: DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Values.global.usersDbSecret }}
                                key: password
                  command:
                      - "/bin/sh"
                      - "-c"
                  args:
                      - |
  {{- end -}}