apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: grafana-cert
    namespace: {{ .Values.global.monitoringNs }}
spec:
    isCA: false
    duration: 10000h
    renewBefore: 360h
    commonName: {{ .Values.grafanaCn }}
    dnsNames:
        - {{ .Values.grafanaCn }}
    ipAddresses:
        - 127.0.0.1
    secretName: {{ .Values.global.grafanaSecretName }}
    privateKey:
        algorithm: RSA
        encoding: PKCS1
        size: 4096
    issuerRef:
        name: {{ .Values.caIssuerName }}
        kind: ClusterIssuer
        group: cert-manager.io