apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{ .Values.kafka.name }}
    name: {{ .Values.kafka.service }}
    namespace: {{ .Values.kafka.namespace }}
spec:
    ports:
        - name: internal
          port: 29092
          targetPort: 29092
        - name: external
          port: 30092
          targetPort: 9093
    selector:
        app: {{ .Values.kafka.name }}
    clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ .Values.kafka.name }}
    namespace: {{ .Values.kafka.namespace }}
    labels:
        app: {{ .Values.kafka.name }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.kafka.name }}
    template:
        metadata:
            labels:
                app: {{ .Values.kafka.name }}
        spec:
            volumes:
                -   name: stores
                    secret:
                        secretName: kafka-store-secret
                        items:
                            - key: broker-keystore.jks
                              path: stores/broker-keystore.jks
                            - key: broker-truststore.jks
                              path: stores/broker-truststore.jks
            containers:
                - name: {{ .Values.kafka.service }}
                  image: 'confluentinc/cp-kafka:7.0.0'
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 29092
                      - containerPort: 9093
                  volumeMounts:
                      -   mountPath: /home/appuser/certs
                          name: stores
                          readOnly: true
                  env:
                      - name: KAFKA_SSL_KEYSTORE_LOCATION
                        value: /home/appuser/certs/stores/broker-keystore.jks
                      - name: KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
                        value: ""
                      - name: KAFKA_SSL_TRUSTSTORE_LOCATION
                        value: /home/appuser/certs/stores/broker-truststore.jks
                      - name: KAFKA_SSL_KEYSTORE_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: kafka-store-passwords
                                key: broker-store-pwd
                      - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: kafka-store-passwords
                                key: broker-store-pwd
                      - name: KAFKA_SSL_KEY_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: kafka-store-passwords
                                key: key-store-pwd
                  envFrom:
                      - configMapRef:
                            name: {{ .Values.kafka.configMap }}
    serviceName: {{ .Values.kafka.service }}