apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.kafka.configMap }}
    namespace: {{ .Values.kafka.namespace }}
data:
    KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-service:9092,EXTERNAL://:30092"
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT"
    KAFKA_ZOOKEEPER_CONNECT: "{{ .Values.zookeeper.service }}:{{ .Values.zookeeper.port }}"
    ALLOW_PLAINTEXT_LISTENER: "yes"
    KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    KAFKA_BROKER_ID: "1"
