apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.kafka.configMap }}
    namespace: {{ .Values.kafka.namespace }}
data:
    KAFKA_ADVERTISED_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9093"
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
    KAFKA_SSL_CLIENT_AUTH: "required"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:SSL"
    KAFKA_ZOOKEEPER_CONNECT: "{{ .Values.zookeeper.service }}:{{ .Values.zookeeper.port }}"
    KAFKA_ZOOKEEPER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
    KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
    KAFKA_LOG_RETENTION_MS: "300000"
    KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: "50000"
    KAFKA_LOG_RETENTION_BYTES: "10485760"