apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.zookeeper.service }}
    namespace: {{ .Values.kafka.namespace }}
spec:
    ports:
        - name: zookeeper-port
          port: {{ .Values.zookeeper.port }}
          targetPort: {{ .Values.zookeeper.port }}
    selector:
        app: {{ .Values.zookeeper.name }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.zookeeper.name }}
    namespace: {{ .Values.kafka.namespace }}
    labels:
        app: {{ .Values.zookeeper.name }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.zookeeper.name }}
    template:
        metadata:
            labels:
                app: {{ .Values.zookeeper.name }}
        spec:
            containers:
                - image: confluentinc/cp-zookeeper:7.3.2
                  imagePullPolicy: IfNotPresent
                  name: zookeeper
                  ports:
                      - containerPort: {{ .Values.zookeeper.port }}
                  env:
                      - name: ZOOKEEPER_CLIENT_PORT
                        value: {{ .Values.zookeeper.port | quote }}
                      - name: ZOOKEEPER_TICK_TIME
                        value: {{ .Values.zookeeper.kickTime | quote }}
