apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.zookeeper.service }}
    namespace: {{ .Values.kafka.namespace }}
spec:
    ports:
        - name: zookeeper-port
          port: {{ .Values.zookeeper.port }}
          targetPort: {{ .Values.zookeeper.port }}
    selector:
        app: {{ .Values.zookeeper.name }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ .Values.zookeeper.name }}
    namespace: {{ .Values.kafka.namespace }}
spec:
    serviceName: {{ .Values.zookeeper.service }}
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.zookeeper.name }}
    template:
        metadata:
            labels:
                app: {{ .Values.zookeeper.name }}
        spec:
            securityContext:
                fsGroup: 1000
            enableServiceLinks: false
            containers:
                - name: zookeeper
                  imagePullPolicy: IfNotPresent
                  image: confluentinc/cp-zookeeper:7.3.2
                  ports:
                      - containerPort: {{ .Values.zookeeper.port }}
                  envFrom:
                      - configMapRef:
                            name: {{ .Values.zookeeper.configMap }}
                  volumeMounts:
                      - mountPath: {{ .Values.zookeeper.mountDataPath }}
                        name: zookeeper-data
                      - mountPath: {{ .Values.zookeeper.mountLogPath }}
                        name: zookeeper-log
            hostname: zookeeper
            restartPolicy: Always
    volumeClaimTemplates:
        - metadata:
              name: zookeeper-data
          spec:
              accessModes:
                  - ReadWriteOnce
              resources:
                  requests:
                      storage: 200Mi
        - metadata:
              name: zookeeper-log
          spec:
              accessModes:
                  - ReadWriteOnce
              resources:
                  requests:
                      storage: 200Mi
